import{S as m,i as c}from"./assets/vendor-8c59ed88.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const y="44800036-3797b6ab3e55b410f8e06bcc9",p="https://pixabay.com/api/";async function g(o){const n=`${p}?key=${y}&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true`;try{const r=await fetch(n);if(!r.ok)throw new Error("Failed to fetch images");return r.json()}catch(r){throw console.error("Error fetching images:",r),r}}let a;function h(){const o=document.querySelector(".gallery");o.innerHTML=""}function b(o){const n=document.querySelector(".gallery"),r=o.map(({webformatURL:i,largeImageURL:e,tags:t,likes:s,views:u,comments:d,downloads:f})=>`
      <a class="gallery-item" href="${e}">
        <img src="${i}" alt="${t}" loading="lazy"/>
        <div class="info">
          <p class="info-item"><b>Likes:</b> ${s}</p>
          <p class="info-item"><b>Views:</b> ${u}</p>
          <p class="info-item"><b>Comments:</b> ${d}</p>
          <p class="info-item"><b>Downloads:</b> ${f}</p>
        </div>
      </a>
    `).join("");n.insertAdjacentHTML("beforeend",r),a?a.refresh():a=new m(".gallery a")}function L(){c.info({title:"Sorry",message:"There are no images matching your search query. Please try again!"})}function w(){document.querySelector(".loader").classList.remove("hidden")}function S(){document.querySelector(".loader").classList.add("hidden")}const l=document.querySelector("#search-form"),q=l.querySelector("input");l.addEventListener("submit",async o=>{o.preventDefault();const n=q.value.trim();if(n){h(),w();try{const r=await g(n);r.hits.length===0?L():b(r.hits)}catch(r){console.error("Error:",r),c.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{S()}}});
//# sourceMappingURL=commonHelpers.js.map
